# Rationale

## Narrative rationale

Community is a central but nebulous concept in sociology. To develop a more precise understanding of community, this reading list brings together structural and cultural theories. I conceptualize community in several interrelated ways: as a cohesive grouping emerging from social relations, as a perception of groupness arising from nominal categories, and as the emotional and symbolic force of solidarity and belonging. Community is socially constructed and reproduced through an interaction of networks and meanings. Together, tastes and ties can produce a range of coherent and distinct groups within a society. Some often-salient categories serve as examples of these dynamics, including race/ethnicity/nation, religion, and sexuality.

Where the first section considers the emergence of cohesive groups within a society at the macro level, the second section shifts attention to micro-level practices of inclusion and exclusion. These practices provide mechanisms for the maintenance of distinct communities. The reading list emphasizes how these practices feed into the power relations between the community of the majority (or the privileged) and communities of marginalized groups. These latter groups could be marginal merely because they are a numeric minority, or because they are denied access to resources and institutions. I focus on what people do in practice, rather how they identify. However, when several social identity categories are available as potentially salient for organizing actual groups, I consider how those axes of identity intersect or interact. Specific processes to consider in this section are relational integration and conflict, cultural assimilation of values, and the maintenance of purity through stigma and ritual.

The final section of the exam addresses why and how the existence of community matters for social life. In tandem, it considers the consequences of change in community. I pay particular attention to changes mediated by two factors related to the abstract concept of scale: geography and technology. Specifically, I mean the spatial process of urbanization and the technical process of improvements in communication technology. Whether maintained or changed by these processes, community is consequential at multiple levels. For individuals, a desire for community provides one possible motivation for social action, and a threatened or perceived loss of community can spur action as well. Collective actors also make use of community; social movements leverage community ties for political action, and formal organizations like corporations and the state can appropriate the informal groupings of community for their own ends.

## Organizing themes and questions

**[Structure, culture, and the (re)production of community.](#scr)**

What are the social processes by which a sense of community is created, sustained, or lost? How do network structures and cultural meanings interact to produce and reproduce bounded social groups which individuals can perceive and to which they can  feel that they belong?

**[Practices of inclusion and exclusion.](#pie)**

What micro-level, interactional practices work to create community? When do social identity categories become salient axes for organizing communities? How do ordinary people and researchers understand these different identities operating simultaneously---as analogous, competing, or intersecting?

How do different communities interact, especially across differentials of power? How do they maintain distinctions, or merge? What role do visibility and stigma play in the marginalization and stratification of minority groups?

**[Changes and consequences.](#cc)**

How does scale, from local to global, shape the experience of or even possibility for community? What is the continued salience of physical space for shaping local difference, against the ability of technology to homogenize and unify at bigger scales?

What does community do for people? Does it provide a motivation for participation in social action, and a meaningful object for people to attach to---for instance, a reason to care about the fates of some places and not others? Community is typically conceived of as informal, bottom-up and organic---when and how is it coopted, by formal organizations, corporations, or the state?
