# Reading Notes

[Reading notes will live here.]

## Collins, "The New Politics of Community"

@collins_new_2010

\fullcite{collins_new_2010}

[this was the 2009 ASA presidential address. it's useful because it's an opinionated take on the state of a particular facet of the discipline. it happens to be one that resonates strongly with me.]

links "community" to power relations, which are about knowledge and culture, symbol and structure

link to Jennifer Nash: discussion of political love

Tönnies: family, community, love

idea of community used to reinforce and challenge social inequalities

analogy with feminist politicization of the family

the construct of community is neglected *because* associated with women, ethnic groups, religious minorities, etc

why community?

- language of community is ubiquitous in US; often associated with place, neighborhood
- versatile, malleable, easy to use, but taken-for-granted
- varied/contradictory meanings & practices
- strong feeling, motivator for action
- matters to everyday experience of social inequalities

[I like *community* because it brings together place, culture, networks. PHC is adding power to that mix (kind of like Talja Blokland).]

[Should I read Du Bois, The Philadelphia Negro, as a classic community study?]

communities as political projects (discusses five sites, with criteria)

- gated communities (real/metaphor, public/private): boundary work
- grassroots politics (language of community)
- imagined communities (nations, beyond face-to-face, mediation---and its consequences for the powerful center)

    - bottom-up public sphere? [she's still optimistic, but this was 2009];
    - beyond geography?

    This is key, though:

    > When reframed through power relations, imagined communities can be marshaled for oppressive or emancipatory political projects.

- community service (military vs care work)
- community organizing (identity and affinity politics; she's not into this binary; links it to community vs civil society)

again, "intersecting systems of power relations"; community for relational thinking (contrasted to binary thinking in use of categories); helpful for thinking social change & reconfigurations of social space ("In a situation of fluidity and seeming interdependence, who knows who belongs where?"), in context of flexibility and ambiguity (*because* the concept is flexible); symbolic boundary construction; key: community can do both, it's not inherently emancipatory or oppressive; community and democracy/egalitarianism? (US pragmatist tradition, including Du Bois)

> Nineteenth-century African American journalist Ida Wells-Barnett’s anti-lynching crusade illustrates the effectiveness of joining an unshakable commitment to community with a passion for social justice.
> ...
> Black people were not her mass, her mob, her public, her population, or a statistical collection of potential lynching victims—they were her community.

Footnotes situate her in the sociological conversation about community and make her methods and epistemologies more explicit.

[do I like communities because they're a meso-level social construct? PHC says they link individuals to social institutions]

[she applies community to sociology as a discipline in a really reflexive and insightful way]

[this piece makes it obvious how useful sociology of culture is: meanings, boundaries, categories, relational thinking...]

[Nathan Jurgenson was one of her RAs]
